#!/bin/tcsh

if($#argv > 0)then
    set host = $argv[1]
else
    set host = ''
endif

switch ($host)
case "oak"
    rsync --progress -azu *.f90 -e ssh oak:simulation/PIC3D/src/shock/
    breaksw
default
    echo "choose oak"
endsw
