#!/bin/tcsh

if($#argv > 0)then
    set host = $argv[1]
else
    set host = ''
endif

switch ($host)
case "tatara"
    rsync --progress -azu *.f90 -e ssh tatara:simulation/PIC3D/src/shock/
    breaksw
case "k"
    rsync --progress -azu *.f90 -e ssh k:simulation/PIC3D/src/shock/
    breaksw
case "k2"
    rsync --progress -azu *.f90 -e ssh k2:simulation/PIC3D/src/shock/
    breaksw
default
    echo "choose k or k2 or tatara"
endsw
